CREATE SCHEMA IF NOT EXISTS `store_db`;

CREATE TABLE IF NOT EXISTS `store_db`.`users` (
  `uname` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `pass` VARCHAR(16) NULL DEFAULT NULL COMMENT '');