-- MySQL Script generated by MySQL Workbench
-- 10/20/15 11:47:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `store_db` ;

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_db` DEFAULT CHARACTER SET utf8 ;
USE `store_db` ;

-- -----------------------------------------------------
-- Table `store_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store_db`.`users` ;

CREATE TABLE IF NOT EXISTS `store_db`.`users` (
  `uname` VARCHAR(16) NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `pass` VARCHAR(16) NULL DEFAULT NULL,
  `pk_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` INT NULL,
  `address_shipping` VARCHAR(45) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`pk_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store_db`.`products` ;

CREATE TABLE IF NOT EXISTS `store_db`.`products` (
  `pk_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `descriptionShort` VARCHAR(255) NULL,
  `descriptionLong` VARCHAR(8000) NULL,
  `price` DECIMAL(7,2) NULL,
  `quantity` INT NULL,
  `rating` DECIMAL(2,1) NULL,
  `variant_id` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store_db`.`order` ;

CREATE TABLE IF NOT EXISTS `store_db`.`order` (
  `pk_order` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `ordercol` VARCHAR(45) NULL,
  `users_pk_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pk_order`),
  INDEX `fk_order_users_idx` (`users_pk_user` ASC),
  CONSTRAINT `fk_order_users`
    FOREIGN KEY (`users_pk_user`)
    REFERENCES `store_db`.`users` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_db`.`order_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store_db`.`order_has_products` ;

CREATE TABLE IF NOT EXISTS `store_db`.`order_has_products` (
  `fk_order` INT UNSIGNED NOT NULL,
  `fk_product` INT NOT NULL,
  PRIMARY KEY (`fk_order`, `fk_product`),
  INDEX `fk_order_has_products_products1_idx` (`fk_product` ASC),
  INDEX `fk_order_has_products_order1_idx` (`fk_order` ASC),
  CONSTRAINT `fk_order_has_products_order1`
    FOREIGN KEY (`fk_order`)
    REFERENCES `store_db`.`order` (`pk_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_products_products1`
    FOREIGN KEY (`fk_product`)
    REFERENCES `store_db`.`products` (`pk_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store_db`.`review` ;

CREATE TABLE IF NOT EXISTS `store_db`.`review` (
  `pk_review` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `rating` INT NOT NULL,
  `fk_user` INT UNSIGNED NOT NULL,
  `products_pk_product` INT NOT NULL,
  PRIMARY KEY (`pk_review`),
  INDEX `fk_review_users1_idx` (`fk_user` ASC),
  INDEX `fk_review_products1_idx` (`products_pk_product` ASC),
  CONSTRAINT `fk_review_users1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `store_db`.`users` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_products1`
    FOREIGN KEY (`products_pk_product`)
    REFERENCES `store_db`.`products` (`pk_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;